/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class Frame3Personel extends javax.swing.JFrame {

    /**
     * Creates new form FramePersonel
     */
    public Frame3Personel() {
        initComponents();
        TabloGoruntule();
        TablePersonel.setVisible(false);
        ButtonEkle.setVisible(false);
        ButtonSil.setVisible(false);
        
        
    }
    public void TabloGoruntule(){
        TablePersonel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TC", "AD", "SOYAD", "YAŞ", "CİNSİYET", "ID"
            }
        ));        
        try {
            Connection con = Connecter.connect();
            Statement st = con.createStatement();
            ResultSet sonuc = st.executeQuery("SELECT * FROM personel");
            int sutun = sonuc.getMetaData().getColumnCount(); //sütun sayısı hesaplandı
            while(sonuc.next()){
                Object[] satir = new Object[sutun]; //sütun sayısı kadar satır objesi oluştu
                for (int i = 1; i < sutun-1; i++) {  //datalar tabloya yerleştiriliyor
                    satir[i-1] = sonuc.getObject(i); //1 sütundaki veriler satırlara yerleştirilerek dizi oluşuyor
                    
                }
                satir[5] = sonuc.getObject(7);
                ((DefaultTableModel) TablePersonel.getModel()).insertRow(sonuc.getRow() - 1, satir);
            }
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Bağlantı hatası Personel");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePersonel = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        LabelTc = new javax.swing.JLabel();
        LabelAd = new javax.swing.JLabel();
        LabelSoyad = new javax.swing.JLabel();
        TextFieldTc = new javax.swing.JTextField();
        TextFieldAd = new javax.swing.JTextField();
        TextFieldSoyad = new javax.swing.JTextField();
        LabelYas = new javax.swing.JLabel();
        LabelCinsiyet = new javax.swing.JLabel();
        SpinnerYas = new javax.swing.JSpinner();
        RadioButtonErkek = new javax.swing.JRadioButton();
        RadioButtonKadin = new javax.swing.JRadioButton();
        ButtonEkle = new javax.swing.JButton();
        ButtonSil = new javax.swing.JButton();
        ButtonGuncelle = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuPersonelGoruntuleme = new javax.swing.JMenuItem();
        MenuPersonelEkle = new javax.swing.JMenuItem();
        MenuPersonelSil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PERSONEL SAYFASI");

        TablePersonel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TC", "AD", "SOYAD", "YAŞ", "CİNSİYET", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablePersonel.setShowGrid(false);
        TablePersonel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablePersonelMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TablePersonel);

        LabelTc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelTc.setText("TC");

        LabelAd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelAd.setText("AD");

        LabelSoyad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelSoyad.setText("SOYAD");

        LabelYas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelYas.setText("YAŞ");

        LabelCinsiyet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelCinsiyet.setText("CİNSİYET");

        SpinnerYas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        buttonGroup1.add(RadioButtonErkek);
        RadioButtonErkek.setText("ERKEK");

        buttonGroup1.add(RadioButtonKadin);
        RadioButtonKadin.setText("KADIN");
        RadioButtonKadin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonKadinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LabelAd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TextFieldAd))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LabelTc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TextFieldTc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RadioButtonErkek, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonKadin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelYas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SpinnerYas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldTc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelYas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerYas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButtonErkek, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButtonKadin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        ButtonEkle.setBackground(new java.awt.Color(0, 255, 51));
        ButtonEkle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonEkle.setText("EKLE");
        ButtonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEkleActionPerformed(evt);
            }
        });

        ButtonSil.setBackground(new java.awt.Color(255, 0, 0));
        ButtonSil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSil.setText("SİL");
        ButtonSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSilActionPerformed(evt);
            }
        });

        ButtonGuncelle.setBackground(new java.awt.Color(255, 255, 0));
        ButtonGuncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonGuncelle.setText("GÜNCELLE");
        ButtonGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuncelleActionPerformed(evt);
            }
        });

        jMenu1.setText("İŞLEMLER");

        MenuPersonelGoruntuleme.setText("Personel Görüntüle");
        MenuPersonelGoruntuleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPersonelGoruntulemeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPersonelGoruntuleme);

        MenuPersonelEkle.setText("Personel Ekle");
        MenuPersonelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPersonelEkleActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPersonelEkle);

        MenuPersonelSil.setText("Personel Sil");
        MenuPersonelSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPersonelSilActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPersonelSil);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonSil, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ButtonSil, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(ButtonGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablePersonelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePersonelMousePressed
        int select = TablePersonel.getSelectedRow();
        String tc = TablePersonel.getValueAt(select, 0).toString();
        String ad = TablePersonel.getValueAt(select, 1).toString();
        String soyad = TablePersonel.getValueAt(select, 2).toString();
        String yaş = TablePersonel.getValueAt(select, 3).toString();
        String cinsiyet = TablePersonel.getValueAt(select, 4).toString();
        
        TextFieldTc.setText(tc);
        TextFieldAd.setText(ad);
        TextFieldSoyad.setText(soyad);
        SpinnerYas.setValue(Integer.parseInt(yaş));
        if(cinsiyet.equals("Erkek")){
            RadioButtonErkek.setSelected(true);
        }else
            RadioButtonKadin.setSelected(true);
        
    }//GEN-LAST:event_TablePersonelMousePressed

    private void RadioButtonKadinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonKadinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonKadinActionPerformed

    private void MenuPersonelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPersonelEkleActionPerformed
        TextFieldTc.setText("");
        TextFieldAd.setText("");
        TextFieldSoyad.setText("");
        SpinnerYas.setValue(0);
        RadioButtonKadin.setSelected(false);
        RadioButtonErkek.setSelected(false);
        ButtonEkle.setVisible(true);
        ButtonSil.setVisible(false);
    }//GEN-LAST:event_MenuPersonelEkleActionPerformed

    private void MenuPersonelGoruntulemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPersonelGoruntulemeActionPerformed
        TablePersonel.setVisible(true);
    }//GEN-LAST:event_MenuPersonelGoruntulemeActionPerformed

    private void MenuPersonelSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPersonelSilActionPerformed
        ButtonSil.setVisible(true);
        ButtonEkle.setVisible(false);
    }//GEN-LAST:event_MenuPersonelSilActionPerformed

    private void ButtonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEkleActionPerformed
        String tcValue = TextFieldTc.getText();
        String tcRegex = "^[1-9][0-9]{10}$"; // TC nin 11 haneli rakamlardan oluşması beklenir
        if (!tcValue.matches(tcRegex)) {
            JOptionPane.showMessageDialog(null, "Lütfen 11 haneli bir tc giriniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String adValue = TextFieldAd.getText();
        String adRegex = "^[A-ZÇĞİÖŞÜ][a-zçğıöşü]+$"; // isme büyük harfle başlamak için
        if (!adValue.matches(adRegex)) {
            JOptionPane.showMessageDialog(null, "Lütfen ismin sadece ilk harfini büyük giriniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String soyadValue = TextFieldSoyad.getText();
        String soyadRegex = "^[A-ZÇĞİÖŞÜ][a-zçğıöşü]+$"; // soyisme büyük harfle başlamak için
        if (!soyadValue.matches(soyadRegex)) {
            JOptionPane.showMessageDialog(null, "Lütfen soyismin sadece ilk harfini büyük giriniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String tc = TextFieldTc.getText();
        String ad = TextFieldAd.getText();
        String soyad = TextFieldSoyad.getText();
        int yas = (int) SpinnerYas.getValue();
        String cinsiyet = RadioButtonErkek.isSelected() ? "Erkek" : "Kadın";
        String sorgu = "INSERT INTO personel(tc,ad,soyad,yaş,cinsiyet,izin) "
                + "VALUES('" + tc +"','" + ad +"','" + soyad +"'," + yas + ",'" + cinsiyet + "',0)";
        TextFieldTc.setText("");
        TextFieldAd.setText("");
        TextFieldSoyad.setText("");
        SpinnerYas.setValue(0);
        RadioButtonKadin.setSelected(false);
        RadioButtonErkek.setSelected(false);
        try {
            Connection con = Connecter.connect();
            Statement st = con.createStatement();
            st.executeUpdate(sorgu);
            con.close();
            TabloGoruntule();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Kayıt Yapılamadı");
        }
    }//GEN-LAST:event_ButtonEkleActionPerformed

    private void ButtonGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuncelleActionPerformed
        int secilenSatir = TablePersonel.getSelectedRow();
        if(secilenSatir == -1){
            JOptionPane.showMessageDialog(null, "Lütfen tabloyu görüntüleyin ve bir seçim yapın");
        }
        else{
            
            try {
                String id = TablePersonel.getValueAt(secilenSatir, 5).toString();
                String tc = TextFieldTc.getText();
                String ad = TextFieldAd.getText();
                String soyad = TextFieldSoyad.getText();
                String yas = SpinnerYas.getValue().toString();
                String cinsiyet = RadioButtonErkek.isSelected() ? "Erkek" : "Kadın";
                String sorgu = "UPDATE personel SET tc ='"+tc+"', ad ='"+ad+"', soyad ='"+soyad+"', yaş ="+yas+", cinsiyet='"+cinsiyet+"' WHERE id="+id;
                System.out.println(yas);
                Connection con = Connecter.connect();
                Statement st = con.createStatement();
                st.executeLargeUpdate(sorgu);
                con.close();
                TabloGoruntule();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Personel güncelleme hatası");
            }
                 
    
        }
    }//GEN-LAST:event_ButtonGuncelleActionPerformed

    private void ButtonSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSilActionPerformed
        int secilenSatir = TablePersonel.getSelectedRow();
        if(secilenSatir == -1){
            JOptionPane.showMessageDialog(null, "Lütfen tabloyu görüntüleyin ve bir seçim yapın");
        }
        else{
            int secim = JOptionPane.showConfirmDialog(null, "Emin misiniz !!!");
            if(secim == 0){
                try {
                    String id = TablePersonel.getValueAt(secilenSatir, 5).toString();
                    Connection con = Connecter.connect();
                    Statement st = con.createStatement();
                    st.executeUpdate("DELETE FROM personel WHERE id=" + id);
                    con.close();
                    TabloGoruntule();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Silme Hatası");
                }
            }
        }
    }//GEN-LAST:event_ButtonSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3Personel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEkle;
    private javax.swing.JButton ButtonGuncelle;
    private javax.swing.JButton ButtonSil;
    private javax.swing.JLabel LabelAd;
    private javax.swing.JLabel LabelCinsiyet;
    private javax.swing.JLabel LabelSoyad;
    private javax.swing.JLabel LabelTc;
    private javax.swing.JLabel LabelYas;
    private javax.swing.JMenuItem MenuPersonelEkle;
    private javax.swing.JMenuItem MenuPersonelGoruntuleme;
    private javax.swing.JMenuItem MenuPersonelSil;
    private javax.swing.JRadioButton RadioButtonErkek;
    private javax.swing.JRadioButton RadioButtonKadin;
    private javax.swing.JSpinner SpinnerYas;
    private javax.swing.JTable TablePersonel;
    private javax.swing.JTextField TextFieldAd;
    private javax.swing.JTextField TextFieldSoyad;
    private javax.swing.JTextField TextFieldTc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
