/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje;

import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author HP
 */
public class Frame2Anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form FrameAnasayfa
     */
    public Frame2Anasayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        ButtonPersonel = new javax.swing.JButton();
        ButtonIzin = new javax.swing.JButton();
        ButtonAyarlar = new javax.swing.JButton();
        ButtonCikis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANA SAYFA");

        ButtonPersonel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonPersonel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/personelIcon.png"))); // NOI18N
        ButtonPersonel.setText("PERSONEL");
        ButtonPersonel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonPersonel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPersonelActionPerformed(evt);
            }
        });

        ButtonIzin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonIzin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/takvimIcon.png"))); // NOI18N
        ButtonIzin.setText("İZİN");
        ButtonIzin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonIzin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonIzin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIzinActionPerformed(evt);
            }
        });

        ButtonAyarlar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonAyarlar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ayarlarIcon.png"))); // NOI18N
        ButtonAyarlar.setText("AYARLAR");
        ButtonAyarlar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAyarlar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAyarlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAyarlarActionPerformed(evt);
            }
        });

        ButtonCikis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonCikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cikisIcon.png"))); // NOI18N
        ButtonCikis.setText("ÇIKIŞ");
        ButtonCikis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonCikis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCikisActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/personelLabel.png"))); // NOI18N

        jMenu1.setText("SAYFALAR");

        jMenu5.setText("Personel");

        jMenuItem1.setText("Personel Görüntüle");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Personel Ekle");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Personel Sil");
        jMenu5.add(jMenuItem3);

        jMenu1.add(jMenu5);

        jMenu6.setText("İzin");

        jMenuItem4.setText("İzin Ekle-Sil");
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("İzin Durumu");
        jMenu6.add(jMenuItem5);

        jMenu1.add(jMenu6);

        jMenu4.setText("Ayarlar");

        jMenuItem6.setText("Yönetici Ekleme");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Frame Ayarı");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Şifre Değiştirme");
        jMenu4.add(jMenuItem8);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ButtonAyarlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonIzin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(96, 96, 96)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ButtonPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonIzin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonAyarlar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCikis))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIzinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIzinActionPerformed
        Frame4Izin frame1 = new Frame4Izin();
        frame1.setVisible(true);
    }//GEN-LAST:event_ButtonIzinActionPerformed

    private void ButtonAyarlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAyarlarActionPerformed
        Frame5Ayarlar frame1 = new Frame5Ayarlar();
        frame1.setVisible(true);
    }//GEN-LAST:event_ButtonAyarlarActionPerformed

    private void ButtonCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCikisActionPerformed
        Frame1Login frame1 = new Frame1Login();
        frame1.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonCikisActionPerformed

    private void ButtonPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPersonelActionPerformed
        Frame3Personel frame1 = new Frame3Personel();
        frame1.setVisible(true);
    }//GEN-LAST:event_ButtonPersonelActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Frame3Personel frame1 = new Frame3Personel();
        frame1.setVisible(true);
                
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2Anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAyarlar;
    private javax.swing.JButton ButtonCikis;
    private javax.swing.JButton ButtonIzin;
    private javax.swing.JButton ButtonPersonel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
